/* eslint-disable */
// Generated by scripts/api/generate_ts_client.py. Do not edit by hand.
export const OPENAPI_METADATA = {
  "openapi": "3.1.0",
  "info": {
    "title": "MeteoLens API",
    "description": "Backend API for MeteoLens public IMGW-PIB data visualisation.",
    "version": "0.1.0"
  },
  "operations": [
    {
      "method": "POST",
      "path": "/api/v1/archive/backfill/synop-daily",
      "operationId": "backfill_synop_daily_archive_api_v1_archive_backfill_synop_daily_post",
      "summary": "Backfill Synop Daily Archive"
    },
    {
      "method": "GET",
      "path": "/api/v1/compare/warning-station/{station_id}",
      "operationId": "compare_warning_station_api_v1_compare_warning_station__station_id__get",
      "summary": "Compare Warning Station"
    },
    {
      "method": "GET",
      "path": "/api/v1/export/map-state.json",
      "operationId": "export_map_state_json_api_v1_export_map_state_json_get",
      "summary": "Export Map State Json"
    },
    {
      "method": "GET",
      "path": "/api/v1/export/map.geojson",
      "operationId": "export_map_geojson_api_v1_export_map_geojson_get",
      "summary": "Export Map Geojson"
    },
    {
      "method": "GET",
      "path": "/api/v1/export/station/{station_id}.csv",
      "operationId": "export_station_csv_api_v1_export_station__station_id__csv_get",
      "summary": "Export Station Csv"
    },
    {
      "method": "GET",
      "path": "/api/v1/export/station/{station_id}.json",
      "operationId": "export_station_json_api_v1_export_station__station_id__json_get",
      "summary": "Export Station Json"
    },
    {
      "method": "GET",
      "path": "/api/v1/export/station/{station_id}/observations.csv",
      "operationId": "export_station_observations_csv_api_v1_export_station__station_id__observations_csv_get",
      "summary": "Export Station Observations Csv"
    },
    {
      "method": "GET",
      "path": "/api/v1/export/station/{station_id}/observations.json",
      "operationId": "export_station_observations_json_api_v1_export_station__station_id__observations_json_get",
      "summary": "Export Station Observations Json"
    },
    {
      "method": "GET",
      "path": "/api/v1/export/warnings.geojson",
      "operationId": "export_warnings_geojson_api_v1_export_warnings_geojson_get",
      "summary": "Export Warnings Geojson"
    },
    {
      "method": "GET",
      "path": "/api/v1/geometry/datasets",
      "operationId": "list_geometry_datasets_api_v1_geometry_datasets_get",
      "summary": "List Geometry Datasets"
    },
    {
      "method": "GET",
      "path": "/api/v1/location/summary",
      "operationId": "get_location_summary_api_v1_location_summary_get",
      "summary": "Get Location Summary"
    },
    {
      "method": "GET",
      "path": "/api/v1/map/layers",
      "operationId": "get_map_layers_api_v1_map_layers_get",
      "summary": "Get Map Layers"
    },
    {
      "method": "GET",
      "path": "/api/v1/map/timeline",
      "operationId": "get_map_timeline_api_v1_map_timeline_get",
      "summary": "Get Map Timeline"
    },
    {
      "method": "GET",
      "path": "/api/v1/products",
      "operationId": "get_products_api_v1_products_get",
      "summary": "Get Products"
    },
    {
      "method": "GET",
      "path": "/api/v1/products/{product_id}/frames",
      "operationId": "get_product_frames_api_v1_products__product_id__frames_get",
      "summary": "Get Product Frames"
    },
    {
      "method": "GET",
      "path": "/api/v1/products/{product_id}/render/{filename}",
      "operationId": "get_product_render_api_v1_products__product_id__render__filename__get",
      "summary": "Get Product Render"
    },
    {
      "method": "GET",
      "path": "/api/v1/rankings",
      "operationId": "get_rankings_api_v1_rankings_get",
      "summary": "Get Rankings"
    },
    {
      "method": "GET",
      "path": "/api/v1/sources",
      "operationId": "list_sources_api_v1_sources_get",
      "summary": "List Sources"
    },
    {
      "method": "GET",
      "path": "/api/v1/stations",
      "operationId": "list_stations_api_v1_stations_get",
      "summary": "List Stations"
    },
    {
      "method": "GET",
      "path": "/api/v1/stations/compare",
      "operationId": "compare_stations_api_v1_stations_compare_get",
      "summary": "Compare Stations"
    },
    {
      "method": "GET",
      "path": "/api/v1/stations/{station_id}",
      "operationId": "get_station_api_v1_stations__station_id__get",
      "summary": "Get Station"
    },
    {
      "method": "GET",
      "path": "/api/v1/stations/{station_id}/observations",
      "operationId": "get_station_observations_api_v1_stations__station_id__observations_get",
      "summary": "Get Station Observations"
    },
    {
      "method": "GET",
      "path": "/api/v1/status/freshness",
      "operationId": "get_freshness_status_api_v1_status_freshness_get",
      "summary": "Get Freshness Status"
    },
    {
      "method": "GET",
      "path": "/api/v1/warnings",
      "operationId": "list_warnings_api_v1_warnings_get",
      "summary": "List Warnings"
    },
    {
      "method": "GET",
      "path": "/api/v1/warnings/{warning_id}",
      "operationId": "get_warning_api_v1_warnings__warning_id__get",
      "summary": "Get Warning"
    },
    {
      "method": "GET",
      "path": "/health",
      "operationId": "health_health_get",
      "summary": "Health"
    },
    {
      "method": "GET",
      "path": "/health/live",
      "operationId": "live_health_live_get",
      "summary": "Live"
    },
    {
      "method": "GET",
      "path": "/health/ready",
      "operationId": "ready_health_ready_get",
      "summary": "Ready"
    }
  ],
  "schemas": [
    "ArchiveBackfillResponse",
    "CacheSourceState",
    "CacheStatus",
    "CompareResponse",
    "EmptyState",
    "FreshnessResponse",
    "GeometryDatasetStatus",
    "GeometryDatasetsResponse",
    "HTTPValidationError",
    "HealthResponse",
    "LocationSummaryResponse",
    "MapLayerResponse",
    "MapLayersResponse",
    "MapTimelineResponse",
    "ObservationResponse",
    "ProductFramesResponse",
    "ProductsResponse",
    "RankingsResponse",
    "ReadinessResponse",
    "ReadyCheck",
    "SourceDescriptor",
    "SourceFreshnessItem",
    "SourceMetadata",
    "SourcesResponse",
    "StationListItem",
    "StationResponse",
    "StationsResponse",
    "TimelineLayer",
    "ValidationError",
    "WarningResponse",
    "WarningStationComparisonResponse",
    "WarningsResponse"
  ]
} as const;
export type ApiOperationId = typeof OPENAPI_METADATA.operations[number]['operationId'];
export type ApiSchemaName = typeof OPENAPI_METADATA.schemas[number];
