"""Generate lightweight TypeScript OpenAPI metadata for the MeteoLens client.

The SDK keeps handwritten fetch helpers for readability, while this generated
file records the backend OpenAPI operations and schema names used by docs and
drift tests.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
BACKEND = ROOT / "backend"
OUTPUT = ROOT / "packages" / "meteolens-api-client" / "src" / "generated.ts"


def main() -> None:
    sys.path.insert(0, str(BACKEND))
    from app.main import app  # noqa: PLC0415

    schema = app.openapi()
    operations: list[dict[str, str]] = []
    for path, path_item in sorted(schema.get("paths", {}).items()):
        if not isinstance(path_item, dict):
            continue
        for method, operation in sorted(path_item.items()):
            if method.upper() not in {"GET", "POST", "PUT", "PATCH", "DELETE"}:
                continue
            if not isinstance(operation, dict):
                continue
            operations.append(
                {
                    "method": method.upper(),
                    "path": path,
                    "operationId": str(operation.get("operationId") or ""),
                    "summary": str(operation.get("summary") or ""),
                }
            )

    schemas = sorted(
        str(name)
        for name in schema.get("components", {}).get("schemas", {})
    )
    payload: dict[str, Any] = {
        "openapi": schema.get("openapi"),
        "info": schema.get("info", {}),
        "operations": operations,
        "schemas": schemas,
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "\n".join(
            [
                "/* eslint-disable */",
                "// Generated by scripts/api/generate_ts_client.py. Do not edit by hand.",
                f"export const OPENAPI_METADATA = {json.dumps(payload, ensure_ascii=False, indent=2)} as const;",
                "export type ApiOperationId = typeof OPENAPI_METADATA.operations[number]['operationId'];",
                "export type ApiSchemaName = typeof OPENAPI_METADATA.schemas[number];",
                "",
            ]
        ),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
